apiVersion: v1
kind: Service
metadata:
  name: churn-service
spec:
  type: LoadBalancer
  selector:
    app: churn-app
  ports:
    - protocol: TCP
      port: 7861 # port of the services
      targetPort: 7860 # Port of the container